mime_types = {
    "png"  : "image/png",
    "gif"  : "image/gif",
    "jpg"  : "image/jpeg",
    "jpeg" : "image/jpeg",
    "tif"  : "image/tif",
    "tiff" : "image/tiff",
    "ico"  : "image/x-icon",
    "svg"  : "image/svg+xml",
    "css"  : "text/css; charset=utf-8",
    "htm"  : "text/html; charset=utf-8",
    "html" : "text/html; charset=utf-8",
    "xml"  : "text/xml; charset=utf-8",
    "rss"  : "text/xml; charset=utf-8",
    "atom" : "text/xml; charset=utf-8",
    "txt"  : "text/plain; charset=utf-8",
    "el"   : "text/plain; charset=utf-8",
    "js"   : "text/javascript; charset=utf-8",
    "md"   : "text/x-markdown; charset=utf-8",
    "gz"   : "application/octet-stream",
    "ps"   : "application/postscript",
    "eps"  : "application/postscript",
    "pdf"  : "application/pdf",
    "tar"  : "application/x-tar",
    "zip"  : "application/zip",
    "mp3"  : "audio/mpeg",
    "wav"  : "audio/x-wav",
    "flac" : "audio/flac",
    "spx"  : "audio/ogg",
    "oga"  : "audio/ogg",
    "ogg"  : "audio/ogg",
    "ogv"  : "video/ogg",
    "mp4"  : "video/mp4",
    "mkv"  : "video/x-matroska",
    "webm" : "video/webm",
    
}
